export class Student {
    id: number;
    student_name: string;
    student_father: string;
    student_DOB : Date;
    student_mother: string;
    student_category: string; 
    student_gender: string;
    student_nationality: string;
    student_domicile: string;
    student_blood: string;
    student_email: string;
    student_parent_email: string;
    student_ph: number;
    student_father_ph: number;
    student_aadhar: number;
    student_corr_address1: string;
    student_corr_address2: string;
    student_corr_city: string;
    student_corr_district: string;
    student_corr_state: string;
    student_corr_country: string;
    student_corr_pincode: number;
    student_parr_address: string;
    student_parraddress: string;
    student_parrcity: string;
    student_parrdistrict: string;
    student_parrstate: string;
    student_parrcountry: string;
    student_parrpincode: number;
    student_course: string;
   // student_image: string;
   student_batch : string;
   student_fee_pattern: string;
   student_admission_status: string;
  }